import { TableColumn } from "@/types/database";

export const TABLE_CONFIGS: Record<string, TableColumn[]> = {
  oem_brands: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "brand_title", key: "brand_title", label: "Brand Title", type: "text" },
    { id: "brand_description", key: "brand_description", label: "Description", type: "text" },
    { id: "brand_image_url", key: "brand_image_url", label: "Image URL", type: "text" },
    { id: "brand_page", key: "brand_page", label: "Brand Page", type: "text" },
    { id: "subsidiaries", key: "subsidiaries", label: "Subsidiaries", type: "text" },
    { id: "wheel_count", key: "wheel_count", label: "Wheel Count", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  oem_vehicles: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "vehicle_title", key: "vehicle_title", label: "Vehicle Title", type: "text" },
    { id: "vehicle_id_only", key: "vehicle_id_only", label: "Vehicle ID Only", type: "text" },
    { id: "model_name", key: "model_name", label: "Model Name", type: "text" },
    { id: "production_years", key: "production_years", label: "Production Years", type: "text" },
    { id: "production_stats", key: "production_stats", label: "Production Stats", type: "text" },
    { id: "good_pic_url", key: "good_pic_url", label: "Good Pic", type: "text" },
    { id: "bad_pic_url", key: "bad_pic_url", label: "Bad Pic", type: "text" },
    { id: "brand_name", key: "brand_name", label: "Brand", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  oem_wheels: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "wheel_title", key: "wheel_title", label: "Wheel Title", type: "text" },
    { id: "part_numbers", key: "part_numbers", label: "Part Numbers", type: "text" },
    { id: "metal_type", key: "metal_type", label: "Metal Type", type: "text" },
    { id: "color", key: "color", label: "Color", type: "text" },
    { id: "weight", key: "weight", label: "Weight", type: "text" },
    { id: "wheel_offset", key: "wheel_offset", label: "Offset", type: "text" },
    { id: "good_pic_url", key: "good_pic_url", label: "Image URL", type: "text" },
    { id: "image_source", key: "image_source", label: "Image Source", type: "text" },
    { id: "notes", key: "notes", label: "Notes", type: "text" },
    { id: "brand_name", key: "brand_name", label: "Brand", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  oem_bolt_patterns: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "bolt_pattern", key: "bolt_pattern", label: "Bolt Pattern", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  oem_center_bores: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "center_bore", key: "center_bore", label: "Center Bore", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  oem_colors: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "color", key: "color", label: "Color", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  oem_diameters: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "diameter", key: "diameter", label: "Diameter", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  oem_widths: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "width", key: "width", label: "Width", type: "text" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
  users: [
    { id: "id", key: "id", label: "ID", type: "text" },
    { id: "username", key: "username", label: "Username", type: "text" },
    { id: "display_name", key: "display_name", label: "Display Name", type: "text" },
    { id: "avatar_url", key: "avatar_url", label: "Avatar URL", type: "text" },
    { id: "bio", key: "bio", label: "Bio", type: "text" },
    { id: "location", key: "location", label: "Location", type: "text" },
    { id: "member_since", key: "member_since", label: "Member Since", type: "text" },
    { id: "listing_count", key: "listing_count", label: "Listings", type: "number" },
    { id: "created_at", key: "created_at", label: "Created", type: "date" },
    { id: "updated_at", key: "updated_at", label: "Updated", type: "date" },
  ],
};
