#!/usr/bin/env node
/**
 * Full data audit: list every cell we need for every item and generate a to-do list.
 * Writes docs/DATA-AUDIT-TODO.md and prints summary.
 *
 * Prereqs: .env.local has VITE_CONVEX_URL.
 * Run: node scripts/generate_data_audit_todo.mjs
 */

import { config } from "dotenv";
import { resolve } from "path";
import { writeFileSync } from "fs";

config({ path: resolve(process.cwd(), ".env.local") });

const CONVEX_URL = (process.env.VITE_CONVEX_URL || "").replace(/\/$/, "");

async function convexQuery(path, args = {}) {
  const res = await fetch(`${CONVEX_URL}/api/query`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ path, args, format: "json" }),
  });
  const json = await res.json();
  if (json.status !== "success") throw new Error(json.errorMessage || "Convex query failed");
  return json.value;
}

function mdTable(headers, rows) {
  const sep = "| " + headers.map(() => "---").join(" | ") + " |";
  return [
    "| " + headers.join(" | ") + " |",
    sep,
    ...rows.map((r) => "| " + r.join(" | ") + " |"),
  ].join("\n");
}

async function run() {
  if (!CONVEX_URL) {
    console.error("Missing VITE_CONVEX_URL in .env.local");
    process.exit(1);
  }

  const audit = await convexQuery("queries:fullDataAudit", {});

  const lines = [];

  lines.push("# Full data audit: every cell we need per item");
  lines.push("");
  lines.push("Generated by `node scripts/generate_data_audit_todo.mjs`. Use this as the master to-do list for filling missing data.");
  lines.push("");

  // -------------------------------------------------------------------------
  // 1. Master cell list (every field per entity)
  // -------------------------------------------------------------------------
  lines.push("## 1. Cell list — fields we need per entity");
  lines.push("");
  lines.push("**Required** = needed for URLs, display, or core UX. **Optional** = recommended for completeness.");
  lines.push("");

  for (const [table, defs] of Object.entries(audit.fieldDefinitions)) {
    const tableLabel = { brands: "oem_brands", vehicles: "oem_vehicles", wheels: "oem_wheels" }[table] || table;
    lines.push("### " + tableLabel);
    lines.push("");
    lines.push("| Field | Label | Required |");
    lines.push("| --- | --- | --- |");
    for (const f of defs) {
      lines.push("| `" + f.key + "` | " + f.label + " | " + (f.required ? "Yes" : "Optional") + " |");
    }
    lines.push("");
  }

  // -------------------------------------------------------------------------
  // 2. Audit results (per field: total, missing, sample ids)
  // -------------------------------------------------------------------------
  lines.push("## 2. Audit results — missing counts per field");
  lines.push("");

  for (const [table, data] of Object.entries(audit.byTable)) {
    lines.push("### " + table + " (total: " + data.total + " records)");
    lines.push("");
    const rows = data.fields.map((f) => [
      f.field,
      f.label,
      f.required ? "Yes" : "Optional",
      String(data.total),
      String(f.missing),
      f.missing === 0 ? "—" : (f.sampleIds || []).slice(0, 5).join(", "),
    ]);
    lines.push(mdTable(["Field", "Label", "Required", "Total", "Missing", "Sample IDs (first 5)"], rows));
    lines.push("");
  }

  // -------------------------------------------------------------------------
  // 3. To-do list (prioritized: required first, then by count)
  // -------------------------------------------------------------------------
  lines.push("## 3. To-do list — fix missing data");
  lines.push("");
  lines.push("Order: fix **required** fields first, then optional. Within each table, records with the most missing required fields first.");
  lines.push("");

  const todo = audit.todo;
  const totalMissing = audit.totalWithMissing || { brands: todo.brands.length, vehicles: todo.vehicles.length, wheels: todo.wheels.length };

  lines.push("### Summary");
  lines.push("");
  lines.push("- **Brands** with at least one missing field: " + totalMissing.brands);
  lines.push("- **Vehicles** with at least one missing field: " + totalMissing.vehicles);
  lines.push("- **Wheels** with at least one missing field: " + totalMissing.wheels);
  lines.push("");

  lines.push("### Brands — records to fix (id | title | missing fields)");
  lines.push("");
  if (todo.brands.length === 0) {
    lines.push("None. All brands have every cell filled.");
  } else {
    const capNote = totalMissing.brands > todo.brands.length ? " (first " + todo.brands.length + " of " + totalMissing.brands + ")" : "";
    lines.push("Listing" + capNote + ":");
    lines.push("");
    lines.push("| ID | Title | Missing fields |");
    lines.push("| --- | --- | --- |");
    for (const r of todo.brands) {
      lines.push("| " + r.id + " | " + (r.title || "").replace(/\|/g, "\\|").slice(0, 50) + " | " + r.missing.join(", ") + " |");
    }
  }
  lines.push("");

  lines.push("### Vehicles — records to fix (id | title | missing fields)");
  lines.push("");
  if (todo.vehicles.length === 0) {
    lines.push("None. All vehicles have every cell filled.");
  } else {
    const capNote = totalMissing.vehicles > todo.vehicles.length ? " (first " + todo.vehicles.length + " of " + totalMissing.vehicles + ")" : "";
    lines.push("Listing" + capNote + ":");
    lines.push("");
    lines.push("| ID | Title | Missing fields |");
    lines.push("| --- | --- | --- |");
    for (const r of todo.vehicles) {
      lines.push("| " + r.id + " | " + (r.title || "").replace(/\|/g, "\\|").slice(0, 50) + " | " + r.missing.join(", ") + " |");
    }
  }
  lines.push("");

  lines.push("### Wheels — records to fix (id | title | missing fields)");
  lines.push("");
  if (todo.wheels.length === 0) {
    lines.push("None. All wheels have every cell filled.");
  } else {
    const capNote = totalMissing.wheels > todo.wheels.length ? " (first " + todo.wheels.length + " of " + totalMissing.wheels + ")" : "";
    lines.push("Listing" + capNote + ":");
    lines.push("");
    lines.push("| ID | Title | Missing fields |");
    lines.push("| --- | --- | --- |");
    for (const r of todo.wheels) {
      lines.push("| " + r.id + " | " + (r.title || "").replace(/\|/g, "\\|").slice(0, 50) + " | " + r.missing.join(", ") + " |");
    }
  }
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("*Re-run this script after filling data to refresh the to-do list.*");

  const outPath = resolve(process.cwd(), "docs", "DATA-AUDIT-TODO.md");
  writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log("Wrote " + outPath);

  // Print summary to stdout
  console.log("\n--- Summary ---");
  console.log("Brands to fix:", totalMissing.brands);
  console.log("Vehicles to fix:", totalMissing.vehicles);
  console.log("Wheels to fix:", totalMissing.wheels);
  const totalMissingCells = audit.byTable.oem_brands.fields.reduce((s, f) => s + f.missing, 0)
    + audit.byTable.oem_vehicles.fields.reduce((s, f) => s + f.missing, 0)
    + audit.byTable.oem_wheels.fields.reduce((s, f) => s + f.missing, 0);
  console.log("Total missing cells (all fields):", totalMissingCells);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
