// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bclvqqnnyqgzoavgrkke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjbHZxcW5ueXFnem9hdmdya2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUxMjU1MzAsImV4cCI6MjA0MDcwMTUzMH0.K4elBNpHRClDSF7WRMZ4hvL3gCftDGRXgtMRqjfjiaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});